// <auto-generated />
namespace Picheres1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class imager_0 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(imager_0));
        
        string IMigrationMetadata.Id
        {
            get { return "202306031143161_imager_0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
